name: 'Cut Release'

on:
  workflow_dispatch:
    inputs:
      majorVersion:
        description: 'Major version'
        required: true
      minorVersion:
        description: 'Minor version'
        required: false
        default: '0'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create Branch
        uses: actions/github-script@v6
        with:
          script: |
            const majorVersion = ${{ github.event.inputs.majorVersion }};
            const minorVersion = ${{ github.event.inputs.minorVersion }};
            const branchName = `release/${majorVersion}.${minorVersion}`;
            const ref = `refs/heads/${branchName}`;
            const sha = context.sha;
            console.debug(`Creating branch ${branchName} at ${sha}`, context);
            github.rest.git.createRef({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              ref,
              sha,
            });
